spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: classpath:secret.yml

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

logging:
  level:
    com.example.shoppingmallserver.*: DEBUG
